# Generated by Django 4.1.3 on 2022-11-03 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='doc', max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='user_fk',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='document_fk',
            field=models.ForeignKey(db_column='document_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='db.document'),
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='image', max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='order_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
