# Generated by Django 4.1.3 on 2022-11-20 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_document_user_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='user_fk',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
