# Generated by Django 4.1.3 on 2022-11-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_document_user_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='name',
        ),
    ]
