# Generated by Django 3.2 on 2022-11-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_remove_img_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
