# Generated by Django 4.1.3 on 2023-01-08 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_alter_img_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
