# Generated by Django 4.1.3 on 2023-01-08 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_alter_myuser_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='rating',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
